import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from 'next/font/google'
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const oufit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={oufit.className}
      >
        <Provider>
          {children}
        </Provider>
        <Toaster position={'top-right'}/>
      </body>
    </html>
  );
}
